### ISSUE TITLE
Input / select text is invisible when "color: inherit" is set globally in CSS

### ISSUE THREAD

**Issue by kachkaev** [tannerlinsley/react-query-devtools#53]
I'm using ant design, so my global styles contain this statement:

```less
input,
button,
select,
optgroup,
textarea {
  // ...
  color: inherit;
  // ...
}
```

source: [ant-design → global.less](https://github.com/ant-design/ant-design/blob/a51439cbbabef454e35218864fddf0da96e4801e/components/style/core/global.less#L342)

Because of `color: inherit`, the text in the input and in the select ends up being invisible.

![Kapture 2020-08-05 at 22 22 19](https://user-images.githubusercontent.com/608862/89465822-a69c7c80-d76a-11ea-82f3-03d658a55bc6.gif)

The solution would be to define the color from the theme to make sure it is stable regardless of the environment.
